name: Android Debug

on:
  workflow_dispatch:

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Decode google-services.json
        run: echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 --decode > app/google-services.json

      - run: chmod +x gradlew

      - run: ./gradlew testDebugUnitTest

  build_apk:
    needs: run_tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Decode google-services.json
        run: echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 --decode > app/google-services.json

      - run: chmod +x gradlew

      - run: ./gradlew assembleDebug

      - name: Upload APK to Workspace
        uses: actions/upload-artifact@v6
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/*.apk

  upload_to_gcp:
    needs: build_apk
    runs-on: ubuntu-latest
    steps:
      - name: Download APK from Workspace
        uses: actions/download-artifact@v8
        with:
          name: debug-apk
          path: downloaded-apk

      - uses: google-github-actions/auth@v3
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - uses: google-github-actions/setup-gcloud@v3

      - name: Upload to Bucket
        run: |
          apk_path=$(find downloaded-apk -name "*.apk" | head -n 1)
          gsutil cp "$apk_path" gs://debug_android_apks/debug-$(date +%s).apk